### ISSUE TITLE
How to configure connection to MSK via IRSA

### ISSUE THREAD

**Issue by joaocc** [conduktor/conduktor-public-charts#111]
Hi,
We are trying to configure access to MSK using IAM IRSA mode.
```
  - bootstrapServers: b-1.xxxxxxxxx.aaaaaaaaa.c3.kafka.eu-west-1.amazonaws.com:9098,b-2.xxxxxxxxx.aaaaaaaaa.c3.kafka.eu-west-1.amazonaws.com:9098
    id: test-IAM-something
    name: irsa-something
    properties: |
      security.protocol=SASL_SSL
      sasl.mechanism=AWS_MSK_IAM
      sasl.jaas.config=ssoftware.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::000000000000:role/role-supporting-irsa-for-this-service-account";
      sasl.client.
```

however we are receiving several errors.
connection via "normal" IAM access key+secret works well though.

```
[35m2024-09-16T22:41:54,954Z[0;39m [36m[console:ZScheduler-Worker-2][0;39m [1;31mERROR[0;39m i.c.m.i.core.scheduler.TaskScheduler - Uncaught error when executing task metadata.indexer.task on cluster 6b948621-9e29-4928-8d2f-87734b55cc2d.
javax.security.auth.login.LoginException: No LoginModule found for ssoftware.amazon.msk.auth.iam.IAMLoginModule
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:738)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:678)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:676)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:676)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
	... 68 common frames omitted
Wrapped by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for ssoftware.amazon.msk.auth.iam.IAMLoginModule
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:117)
	at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:217)
	... 64 common frames omitted
Wrapped by: org.apache.kafka.common.KafkaException: Failed to create new NetworkClient
	at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:245)
	at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:185)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:503)
	... 62 common frames omitted
Wrapped by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:519)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at zio.kafka.admin.AdminClient$.javaClientFromSettings$$anonfun$1$$anonfun$1$$anonfun$1(AdminClient.scala:1518)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:108)
	at zio.ZIO$.suspendSucceed$$anonfun$1(ZIO.scala:4823)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:989)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1058)
```

Is IRSA supported?
If so, are we missing any parameter?
Thanks

**Comment by wilkejo** [comment]
We have a setup with MSK IAM as well. 

We created a Service Account Role which has permissions to assume a MSK access role.

In the HelmChart

```yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/conduktor-base
```      

Our configuration for the MSK cluster itself looks like yours.

**Comment by joaocc** [comment]
Thanks. That helps a lot. We'll continue checking for the issue elsewhere (like checking IAM permissions). Thx

**Comment by sderosiaux** [comment]
@joaocc just in case, there is a typo in your config above: `ssoftware.` -> `software.`
